spring.application.name=poupeja

server.port=${PORT:9090}

# Conexão do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/local
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Exibir os comandos SQL no console
spring.jpa.show-sql=true

# Ajusta o comportamento do Hibernate gerando as tabelas ou apenas validando
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
