spring.application.name=poupeja
server.port=${PORT:9090}

# Conexao do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# debug SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
